Simulation5/S.MVC/Areas/Admin/Controllers/AtractionController.cs
using System.Collections.ObjectModel;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using S.BL.DTOs.AtractionDTOs;
using S.BL.Services.Abstractions;
using S.Core.Models;

namespace S.MVC.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class AtractionController : Controller
    {
        private readonly IAtractionService _atractionService;

        public AtractionController(IAtractionService atractionService)
        {
            _atractionService = atractionService;
        }

        public async Task<IActionResult> Index()
        {
            try
            {
                ICollection<AtractionUpdateDTO> atraction = await _atractionService.GetAllAsync();
                return View(atraction);
            }
            catch (Exception ex)
            {
                throw new Exception("Something went wrong");

            }
           
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create( AtractionCreateDTO atractionCreate)
        {
            try
            {
                ViewBag.Categories = new SelectList("CategoryId", "Name");
                await _atractionService.CreateAsync(atractionCreate);
                return RedirectToAction(nameof(Create));
            }
            catch (Exception ex)
            {
                return BadRequest(ex);
            }
         
        }
    }
}

Simulation5/S.MVC/Areas/Admin/Controllers/DashboardController.cs
using Microsoft.AspNetCore.Mvc;

namespace S.MVC.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class DashboardController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Simulation5/S.MVC/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;


namespace S.MVC.Controllers
{
    public class HomeController : Controller
    {
       
        public IActionResult Index()
        {
            return View();
        }

       
    }
}

Simulation5/S.MVC/Areas/Admin/Views/Atraction/Create.cshtml
@model AtractionCreateDTO

<div class="container-fluid">
    <form method="post" enctype="multipart/form-data">
        <div class="mb-3">
            <label asp-for="Title" class="form-label">Title</label>
            <input asp-for="Title" type="text" class="form-control">
            <span asp-validation-for="Title" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="Description" class="form-label">Description</label>
            <input asp-for="Description" type="text" class="form-control">
            <span asp-validation-for="Description" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="CategoryId" class="form-label">CategoryId</label>
            <select asp-for="CategoryId"></select>
            <span asp-validation-for="CategoryId" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="Img" class="form-label">Img</label>
            <input asp-for="Img" type="file" class="form-control">
            <span asp-validation-for="Img" class="text-danger"></span>
        </div>
        <button type="submit" class="btn btn-warning text-white">Create</button>
    </form>
</div>

Simulation5/S.MVC/Areas/Admin/Views/Atraction/Index.cshtml
@model ICollection<AtractionUpdateDTO>;

<!-- Begin Page Content -->
<div class="container-fluid">

    <!-- Page Heading -->
    <h1 class="h3 mb-2 text-gray-800">Atraction</h1>

    <a asp-action="Create" asp-controller="Atraction" asp-area="Admin">
        <button class="btn btn-success mb-3">
            Create
        </button>
    </a>

    <!-- DataTales Example -->
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">DataTables Example</h6>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th>Image</th>
                            <th>Title</th>
                            <th>Description</th>
                            
                            <th>Update</th>
                            <th>Delete</th>
                        </tr>
                    </thead>
                    <tbody>

                        @foreach (AtractionUpdateDTO item in Model)
                        {
                            <tr>
                                <td>
                                    <img width="50" src="~/uploads/news/@item.Img" alt="Alternate Text" />
                                </td>
                                <td>@item.Title</td>
                                <td>@item.Description</td>
                                <td>@item.Category.Title</td>
                                <td>
                                     <a asp-controller="Atraction" asp-action="Update" asp-area="Admin" asp-route-id="@item.Id"> 
                                        <button class="btn btn-warning"> 
                                             Update 
                                        </button> 
                                     </a> 
                                </td>
                                <td>
                                    <a asp-controller="Atraction" asp-action="Delete" asp-area="Admin" asp-route-id="@item.Id"> 
                                        <button class="btn btn-danger"> 
                                            Delete 
                                        </button>
                                    </a>
                                </td>
                            </tr>

                        }

                    </tbody>
                </table>
            </div>
        </div>
    </div>

</div>
<!-- /.container-fluid -->

Simulation5/S.MVC/Views/Shared/_Layout.cshtml
<!doctype html>
<html class="no-js" lang="en">

<head>
	<!-- meta data -->
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
	<!--font-family-->
	<link href="https://fonts.googleapis.com/css?family=Poppins:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

	<!-- title of site -->
	<title>Directory Landing Page</title>

	<!-- For favicon png -->
	<link rel="shortcut icon" type="image/icon" href="assets/logo/favicon.png" />

	<!--font-awesome.min.css-->
	<link rel="stylesheet" href="assets/css/font-awesome.min.css">

	<!--linear icon css-->
	<link rel="stylesheet" href="assets/css/linearicons.css">

	<!--animate.css-->
	<link rel="stylesheet" href="assets/css/animate.css">

	<!--flaticon.css-->
	<link rel="stylesheet" href="assets/css/flaticon.css">

	<!--slick.css-->
	<link rel="stylesheet" href="assets/css/slick.css">
	<link rel="stylesheet" href="assets/css/slick-theme.css">

	<!--bootstrap.min.css-->
	<link rel="stylesheet" href="assets/css/bootstrap.min.css">

	<!-- bootsnav -->
	<link rel="stylesheet" href="assets/css/bootsnav.css">

	<!--style.css-->
	<link rel="stylesheet" href="assets/css/style.css">

	<!--responsive.css-->
	<link rel="stylesheet" href="assets/css/responsive.css">

	<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
	<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
	<!--[if lt IE 9]>
		<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
		<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
	<![endif]-->

</head>

<body>
	<!--[if lte IE 9]>
		<p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="https://browsehappy.com/">upgrade your browser</a> to improve your experience and security.</p>
	<![endif]-->
	<!--header-top start -->
	<header id="header-top" class="header-top">
		<ul>
			<li>
				<div class="header-top-left">
					<ul>
						<li class="select-opt">
							<select name="language" id="language">
								<option value="default">EN</option>
								<option value="Bangla">BN</option>
								<option value="Arabic">AB</option>
							</select>
						</li>
						<li class="select-opt">
							<select name="currency" id="currency">
								<option value="usd">USD</option>
								<option value="euro">Euro</option>
								<option value="bdt">BDT</option>
							</select>
						</li>
						<li class="select-opt">
							<a href="#"><span class="lnr lnr-magnifier"></span></a>
						</li>
					</ul>
				</div>
			</li>
			<li class="head-responsive-right pull-right">
				<div class="header-top-right">
					<ul>
						<li class="header-top-contact">
							+1 222 777 6565
						</li>
						<li class="header-top-contact">
							<a href="#">sign in</a>
						</li>
						<li class="header-top-contact">
							<a href="#">register</a>
						</li>
					</ul>
				</div>
			</li>
		</ul>

	</header><!--/.header-top-->
	<!--header-top end -->
            @RenderBody()
       <!--footer start-->
		<footer id="footer"  class="footer">
			<div class="container">
				<div class="footer-menu">
		           	<div class="row">
			           	<div class="col-sm-3">
			           		 <div class="navbar-header">
				                <a class="navbar-brand" href="index.html">list<span>race</span></a>
				            </div><!--/.navbar-header-->
			           	</div>
			           	<div class="col-sm-9">
			           		<ul class="footer-menu-item">
			                    <li class="scroll"><a href="#works">how it works</a></li>
			                    <li class="scroll"><a href="#explore">explore</a></li>
			                    <li class="scroll"><a href="#reviews">review</a></li>
			                    <li class="scroll"><a href="#blog">blog</a></li>
			                    <li class="scroll"><a href="#contact">contact</a></li>
			                    <li class=" scroll"><a href="#contact">my account</a></li>
			                </ul><!--/.nav -->
			           	</div>
		           </div>
				</div>
				<div class="hm-footer-copyright">
					<div class="row">
						<div class="col-sm-5">
							<p>
								&copy;copyright. designed and developed by <a href="https://www.themesine.com/">themesine</a>
							</p><!--/p-->
						</div>
						<div class="col-sm-7">
							<div class="footer-social">
								<span><i class="fa fa-phone"> +1  (222) 777 8888</i></span>
								<a href="#"><i class="fa fa-facebook"></i></a>	
								<a href="#"><i class="fa fa-twitter"></i></a>
								<a href="#"><i class="fa fa-linkedin"></i></a>
								<a href="#"><i class="fa fa-google-plus"></i></a>
							</div>
						</div>
					</div>
					
				</div><!--/.hm-footer-copyright-->
			</div><!--/.container-->

			<div id="scroll-Top">
				<div class="return-to-top">
					<i class="fa fa-angle-up " id="scroll-top" data-toggle="tooltip" data-placement="top" title="" data-original-title="Back to Top" aria-hidden="true"></i>
				</div>
				
			</div><!--/.scroll-Top-->
			
        </footer><!--/.footer-->
		<!--footer end-->
		
		<!-- Include all js compiled plugins (below), or include individual files as needed -->

		<script src="assets/js/jquery.js"></script>
        
        <!--modernizr.min.js-->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/modernizr/2.8.3/modernizr.min.js"></script>
		
		<!--bootstrap.min.js-->
        <script src="assets/js/bootstrap.min.js"></script>
		
		<!-- bootsnav js -->
		<script src="assets/js/bootsnav.js"></script>

        <!--feather.min.js-->
        <script  src="assets/js/feather.min.js"></script>

        <!-- counter js -->
		<script src="assets/js/jquery.counterup.min.js"></script>
		<script src="assets/js/waypoints.min.js"></script>

        <!--slick.min.js-->
        <script src="assets/js/slick.min.js"></script>

		<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.min.js"></script>
		     
        <!--Custom JS-->
        <script src="assets/js/custom.js"></script>
        
    </body>
	
</html>